### PR TITLE
Updated bumps and lmfit controllers to be more robust against parameter names

### LINKED ISSUE #1247: Bumps fails when param names have spaces in
Replacing the self.param_names with something like `[f'p{i}' for (i, _) in enumerate(param_names)]`

### PR DESCRIPTION
**Pull request by AndrewLister-STFC**
## Description of work

Fixes #1247 

Assign numerical parameter names to variables within the context of the bumps controller.
These are only used in a mapping that has to be generated via the use of `eval` as bumps does not allow for **arg expansion.

## Testing Instructions

1.
2.
3.

## Checklist

- [ ] The title is of a format appropriate for a line in future release notes.
- [ ] I have added the appropriate tags to the PR.
- [ ] My PR represents one logical piece of work.
- [ ] My PR fully fixes the issue linked. If new issues have been created, what are they?
- [ ] I have added the appropriate tests to cover code that has been added.
- [ ] I have updated the documentation in the relevant places to cover the changes.

### CODE REVIEW

**Review by RabiyaF — COMMENTED** [review]
I pushed similar changes to the lmfit_controller so that it can allow different syntax of variable names for the parameters in the new mantid data.

**Comment by AnthonyLim23** [comment]
it all works as expected. Is it possible to write a test for this?

**Comment by RabiyaF** [comment]
I added tests. Let me know if anything else is needed. It would be great to get it merged this week (before the mantid meeting next week).

**Review by AnthonyLim23 — APPROVED** [review]
Looks good to me

**Pull request merged**
