### PR TITLE
Add missing dependencies to setup

### PR DESCRIPTION
**Pull request by robertapplin**
#### Description of Work
This PR adds the `tinycc` dependency for SASView to the setup.py . Without this, it was not possible to run a benchmark using one of the SAS datasets in a different software.

The `h5py` and `pyyaml` dependencies for mantid have also been added to the setup.py. Without these, you would see a number of python warnings when running a benchmark using the mantid software. Such as:
```
Python-[Warning] Failed to load plugin C:/MantidInstall/plugins/python\algorithms/WorkflowAlgorithms/SANS/SANSReductionCoreEventSlice.py.
Error: Traceback (most recent call last):
  File "C:\MantidInstall\bin\mantid\kernel\plugins.py", line 201, in load_from_file
    name, module = load_plugin(filepath)
  File "C:\MantidInstall\bin\mantid\kernel\plugins.py", line 221, in load_plugin
    module = loader.run()
  File "C:\MantidInstall\bin\mantid\kernel\plugins.py", line 66, in run
    return SourceFileLoader(name, pathname).load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:/MantidInstall/plugins/python\algorithms/WorkflowAlgorithms/SANS/SANSReductionCoreEventSlice.py", line 12, in <module>
    from SANSReductionCoreBase import SANSReductionCoreBase
  File "C:/MantidInstall/plugins/python\algorithms/WorkflowAlgorithms/SANS\SANSReductionCoreBase.py", line 20, in <module>
    from sans.algorithm_detail.mask_sans_workspace import mask_workspace
  File "C:\MantidInstall\scripts\SANS\sans\algorithm_detail\mask_sans_workspace.py", line 7, in <module>
    from sans.algorithm_detail.mask_workspace import create_masker
  File "C:\MantidInstall\scripts\SANS\sans\algorithm_detail\mask_workspace.py", line 15, in <module>
    from sans.common.file_information import (find_full_file_path, get_instrument_paths_for_sans_file)
  File "C:\MantidInstall\scripts\SANS\sans\common\file_information.py", line 12, in <module>
    import h5py as h5
ModuleNotFoundError: No module named 'h5py'
```

*No related issue because this was a quick issue to solve*

#### Testing Instructions

1. You should be able to run the following benchmark `fitbenchmarking -o examples/options_template.ini -p examples/benchmark_problems/SAS_modelling/SASView_Complex_Shapes_1D/`

with options file

```
[FITTING]

software: mantid

num_runs: 1
max_runtime: 30

[MINIMIZERS]

bumps: lm-bumps
       mp

scipy_ls: lm-scipy

mantid:  Simplex

[PLOTTING]

make_plots: yes
results_dir: C:\Users\mlc47243\Documents\fb-results\sas_complex\

[LOGGING]

external_output: log_only
# Note: default for external_output is log_only, meaning information is
# printed to log file but not the stdout stream. For more information
# see the fitbenchmarking docs
```

without seeing a sasview error or a mantid warning.

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

### CODE REVIEW

**Comment by AndrewLister-STFC** [comment]
I don't have tinycc on my machine, perhaps it's a windows specific requirement. I've never used it but perhaps we should look into platform specific dependencies for this: https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies

**Comment by robertapplin** [comment]
> I don't have tinycc on my machine, perhaps it's a windows specific requirement. I've never used it but maybe we should look into platform specific dependencies for this: https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies

Looks like you are right, its a windows-only requirement https://www.sasview.org/docs/dev/sasmodels-api/sasmodels.html . That sounds like a good idea :)

**Comment by robertapplin** [comment]
It's worth noting that a large project to overhaul the dependency management system in mantid is currently underway, so it might be possible to remove the extra mantid dependencies added in the setup in around 6 months to a year.

**Review by AndrewLister-STFC — APPROVED** [review]

**Comment by AndrewLister-STFC** [comment]
I'll wait to update and merge this after the other one is merged.

**Pull request merged**
