### PR TITLE
Load problem descriptions for `NIST`, `Mantid`, `SASView` and `IVP` 

### LINKED ISSUE #948: Load the problem descriptions into the FittingProblem as part of parsing
**Is your feature request related to a problem? Please describe.**
Many problems have a description in the problem definition file. This should be displayed in the results pages. There is a place for it in the FittingProblem but none of the parsers use it yet.

### PR DESCRIPTION
**Pull request by robertapplin**
#### Description of Work
This PR makes sure the problem descriptions are loaded for NIST, Mantid, SASView and IVP problem files. There doesn't seem to be a description option for `CUTEst` format in here so its been left out:
https://github.com/jfowkes/pycutest/blob/15794b214756f0cd54cde9e453304abc2eb8d42b/pycutest/problem_class.py#L41

I have also made the sections in the Fitting reports collapsible just like they are in the problem summary pages.

Fixes #948 

#### Testing Instructions

1. Run a benchmark of a mantid, NIST, SASView and IVP problem. Look at a comparison table and click the problem name - there should be a description at the top of the page that is open.
2. There should be no change to CUTEst
3. Check that the Fitting Reports have a problem description and that each section is collapsible

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

### CODE REVIEW

**Comment by AndrewLister-STFC** [comment]
I'm just running this to sign off, but all looks good. With the SIF files, there seems to be a convention that it has a description as a comment (which pycutest ignores). Let's leave it out of this one as you say but I'll make an issue to parse it ourselves instead of through pycutest.

**Comment by AndrewLister-STFC** [comment]
@robertapplin I've checked it and am happy to merge. Can you just put a second pair of eyes on the updates I  just pushed making the descriptions visible in some of the old files where they were still comments.

**Comment by robertapplin** [comment]
> @robertapplin I've checked it and am happy to merge. Can you just put a second pair of eyes on the updates I just pushed making the descriptions visible in some of the old files where they were still comments.

Your changes look good, thanks for updating those 👍

**Review by AndrewLister-STFC — CHANGES_REQUESTED** [review]
Almost forgot. I think the docs will need an update to metion what the description is used for... I think we have it saying "currently unused" or something at the moment

**Review by AndrewLister-STFC — APPROVED** [review]

**Pull request merged**
