### PR TITLE
Issue #228: Fix missed relative imports, and some indents.

### LINKED ISSUE #228: In example scripts have all import at the top
Change to absolute import. Aim in example scripts to get rid of

```
# Insert path to where the scripts are located, relative to
# the example_scripts folder
current_path = os.path.dirname(os.path.realpath(__file__))
fitbenchmarking_folder = os.path.abspath(os.path.join(current_path, os.pardir))
scripts_folder = os.path.join(fitbenchmarking_folder, 'fitbenchmarking')
sys.path.insert(0, scripts_folder)
sys.path.insert(1, fitbenchmarking_folder)
```

### PR DESCRIPTION
**Pull request by AndrewLister-STFC**
#### Description of Work

Fixes #228 

Updated imports that were missed in last PR for this issue.

#### Testing Instructions

1. Run tests

### CODE REVIEW

**Comment by tyronerees** [comment]
This doesn't run for me -- I get 
```
~/fitbenchmarking$ python example_scripts/example_runScripts.py
Traceback (most recent call last):
  File "example_scripts/example_runScripts.py", line 18, in <module>
    from fitbenchmarking.fitting_benchmarking import do_fitting_benchmark as fitBenchmarking
ImportError: No module named fitbenchmarking.fitting_benchmarking
```
Running `sudo setup.py install` again makes no difference.

**Comment by AndrewLister-STFC** [comment]
> This doesn't run for me -- I get
> ~/fitbenchmarking$ python example_scripts/example_runScripts.py
> Traceback (most recent call last):
>   File "example_scripts/example_runScripts.py", line 18, in <module>
>     from fitbenchmarking.fitting_benchmarking import do_fitting_benchmark as fitBenchmarking
> ImportError: No module named fitbenchmarking.fitting_benchmarking
> 
> Running sudo setup.py install again makes no difference.

Talked wth Tyrone. Issues seem to come from package data in setup.py?

**Comment by arm61** [comment]
In order to get tests passing (where the are .dat, .txt files) I added some stuff to the package data in the setup.py. This may be causing issues (that really travis should be catching but oh well :) )

**Comment by AndrewLister-STFC** [comment]
> In order to get tests passing (where the are .dat, .txt files) I added some stuff to the package data in the setup.py. This may be causing issues (that really travis should be catching but oh well :) )

My next task is adding the example scripts to the test suite for just this reason.

**Comment by tyronerees** [comment]
@AndrewLister-STFC  -- just to record what I told you earlier: I need `package_data={'fitbenchmarking': ['resproc/color_definitions.txt']}` to get the example script running, but not the others (although I haven't run the tests locally).   

As reported by @Anders-Markvardsen in https://github.com/fitbenchmarking/fitbenchmarking/pull/225#issuecomment-533975855, adding `benchmark_problems` to `package_data` actually seems to break the example script for me too.

**Comment by AndrewLister-STFC** [comment]
This is pretty closely related to #226 (in that thats where the fixes for the setup have been added)

**Pull request merged**
