### PR TITLE
Added bundle adjustment problems

### PR DESCRIPTION
**Pull request by jess-farmer**
## Description of work

Add in bundle adjustment problems in order to test new sparse jacobian features 

To do 

- [x] Get initial Ladybug problem working
- [x] Add more problems
- [x] Add tests
- [x] Sort out plotting/fitting report
- [x] Add documentation

Fixes # 

## Testing Instructions

1. Run Fitbenchmarking with the `Bundle_Adjustment` problem set and scipy_ls minimizers trf and dogbox
2.
3.

## Checklist

- [x] The title is of a format appropriate for a line in future release notes.
- [x] I have added the appropriate tags to the PR.
- [x] My PR represents one logical piece of work.
- [x] My PR fully fixes the issue linked. If new issues have been created, what are they?
- [x] I have added the appropriate tests to cover code that has been added.
- [x] I have updated the documentation in the relevant places to cover the changes.

### CODE REVIEW

**Review by tyronerees — COMMENTED** [review]
Here is the output I get: 

image
with this ini file: 
```
[FITTING]

software: scipy_ls

num_runs: 1
max_runtime: 600
cost_func_type: weighted_nlls
		nlls
[MINIMIZERS]

scipy_ls: trf
	  dogbox
# scipy: bfgs

# Note: this will not run unless ralfit is added to `software` in [FITTING]
ralfit: gn

[JACOBIAN]
scipy: 2-point_sparse

[OUTPUT]

make_plots: yes

# results_dir: new_results/

[LOGGING]

external_output: log_only
# Note: default for external_output is log_only, meaning information is
# printed to log file but not the stdout stream. For more information
# see the fitbenchmarking docs

```

**Comment by tyronerees** [comment]
I can confirm that your ini file works for me.  It seems the problem must be something to do with looking for an analytic jacobian first -- even though this should default back to scipy, this doesn't seem to work for the plotting. Here's the output I get for my original ini file: 

image

vs this for yours: 

image

**Comment by jess-farmer** [comment]
Yeah this seems very strange! I can confirm that I get the same output as you when using your ini file, and everything takes much longer to run - I'll have a think about why this is the case.

**Comment by jess-farmer** [comment]
Having tried a few different options files, I think that the problem is actually the cost function type - `weighted_nlls` is okay but `nlls` isn't

**Review by tyronerees — APPROVED** [review]
Thanks, Jess -- I'm happy with this wording

**Pull request merged**
