### PR TITLE
Added `best_available` jacobian option to allow for sets with only some analytic

### PR DESCRIPTION
**Pull request by AndrewLister-STFC**
## Description of work

While reviewing #1231 I was getting a weird error (@AnthonyLim23's bug finding skills must be rubbing off!):

Running: `fitbenchmarking -o tmp.ini -p examples/benchmark_problems/simple_tests/ -s scipy scipy_ls -e debug -d`

With:
<details>

<summary> tmp.ini </summary>

```
[FITTING]

hes_method: scipy
            numdifftools

[MINIMIZERS]

scipy: dogleg

scipy_ls: dogbox

[HESSIAN]

scipy: 3-point
```

</details>

<details>
<summary>Error message</summary>

```
Unknown exception. Exiting.
Traceback (most recent call last):
  File "/home/alister/venvs/fitbenchmarking/bin/fitbenchmarking", line 33, in <module>
    sys.exit(load_entry_point('FitBenchmarking', 'console_scripts', 'fitbenchmarking')())
  File "/home/alister/fitbenchmarking/fitbenchmarking/cli/main.py", line 432, in main
    run(problem_sets=args.problem_sets,
  File "/home/alister/fitbenchmarking/fitbenchmarking/cli/exception_handler.py", line 29, in wrapped
    return f(*args, **kwargs)
  File "/home/alister/fitbenchmarking/fitbenchmarking/cli/main.py", line 326, in run
    save_results(group_name=label,
  File "/home/alister/fitbenchmarking/fitbenchmarking/utils/write_files.py", line 29, in wrapper
    return function(*args, **kwargs)
  File "/home/alister/fitbenchmarking/fitbenchmarking/core/results_output.py", line 69, in save_results
    best_results, results_dict = preprocess_data(results)
  File "/home/alister/fitbenchmarking/fitbenchmarking/core/results_output.py", line 158, in preprocess_data
    results, all_result_tags = _handle_fallback_tags(results,
  File "/home/alister/fitbenchmarking/fitbenchmarking/core/results_output.py", line 268, in _handle_fallback_tags
    if update_summary[sm_tag] in ['jacobian', 'both']:
KeyError: ('scipy_ls', 'dogbox')
```

</details>

The logic to figure out how to combine the tags was pretty complicated and I couldn't remember how it worked so I tried this out.

Making a PR in case this is something others have seen and wanted a patch for!

Changes in this PR:
- Jacobian is called "best_available" for the default.
- Single runs cannot result in fragmented tables.
- Logic in results processing is much less complex.

Downsides:
- "best_available" is descriptive for the table but not for individual runs
- the new jacobian uses `__getattr__` and `__setattr__` which could be confusing

## Checklist

- [x] The title is of a format appropriate for a line in future release notes.
- [ ] I have added the appropriate tags to the PR.
- [ ] My PR represents one logical piece of work.
- [ ] My PR fully fixes the issue linked. If new issues have been created, what are they?
- [ ] I have added the appropriate tests to cover code that has been added.
- [ ] I have updated the documentation in the relevant places to cover the changes.

### CODE REVIEW

**Review by RabiyaF — CHANGES_REQUESTED** [review]
This is a much better approach to handle the fallback cases. 

I ran `fitbenchmarking -o tmp.ini -p examples/benchmark_problems/simple_tests/ -s scipy scipy_ls -e debug -d` and I think it miscalculates the `expected_count = len(rows) in _get_all_result_tags` 
(If I remember correctly) There are repeating tags and that is what throws off the expected_count and then the subsequent calculations. I think if we figure out a way to fix it then it would only complicate the logic even further.

So, I much prefer your method of introducing a new jacobian class :thumbsup: It is much cleaner and maintainable way of doing this.

**Comment by AndrewLister-STFC** [comment]
@RabiyaF One of the pylint complaints is not reimplementing the abstract methods. It' currently covered by the get_attribute and set_attribute calls, but perhaps this would be cleaner/neater/more readable. Which do you prefer?
```
"""
Module which acts as a analytic Jacobian calculator when available, otherwise
uses a trusted software to approximate.
"""
from typing import Any

from fitbenchmarking.jacobian.analytic_jacobian import Analytic
from fitbenchmarking.jacobian.base_jacobian import Jacobian
from fitbenchmarking.jacobian.scipy_jacobian import Scipy
from fitbenchmarking.utils.log import get_logger

LOGGER = get_logger()


class BestAvailable(Jacobian):
    """
    Class to apply an analytical Jacobian if available -- otherwise choose a
    scipy one.
    """

    def __init__(self, problem):
        # pylint: disable=super-init-not-called
        if callable(problem.jacobian):
            self.sub_jac = Analytic(problem)
            self.sub_jac.method = 'default'
        else:
            self.sub_jac = Scipy(problem)
            self.sub_jac.method = '2-point'

    def eval(self, params, **kwargs):
        """
        Evaluates Jacobian of the model, :math:`\\nabla_p f(x,p)`,
        at the point given by the parameters.

        :param params: The parameter values at which to evaluate the Jacobian
        :type params: list

        :return: Computed Jacobian
        :rtype: numpy array
        """
        return self.sub_jac.eval(params, **kwargs)

    @property
    def method(self):
        """
        Utility function to get the numerical method

        :return: the names of the parameters
        :rtype: list of str
        """
        return self.sub_jac.method

    @method.setter
    def method(self, value):
        """
        Utility function to set the numerical method

        :param value: the name of the numerical method
        :type value: str
        """
        if value != "default":
            LOGGER.warning("Method cannot be selected for best_available, "
                           "using default of %s.", self.sub_jac.method)

    def name(self) -> str:
        """
        Get a name for the current status of the jacobian.

        :return: A unique name for this jacobian/method combination
        :rtype: str
        """
        return "best_available"
```

**Review by RabiyaF — CHANGES_REQUESTED** [review]
I think these changes will be more maintainable in the long run than the convoluted matching logic 👍🏼 . 

There are minor suggested changes to the docs of the hessian tests. 

I have left a question for a part of the code that is not covered by a test. Maybe there is a way to test that part but I am not 100% sure if that part of the code can be called.

And also, I think these files can be removed:

1. `fallbackcase1.json`
2. `fallbackcase2.json`
3. `fallbackcase3.json`
4. `fallbackcase4.json`
5. `fallbackcase5.json`
6. `fallbackcase6.json`
7. `fallbackcase7.json`

**Review by RabiyaF — APPROVED** [review]
All looks good to me 👍🏼

**Pull request merged**
