### PR TITLE
Fitting benchmark test

### PR DESCRIPTION
**Pull request by bb511**
#### Description of Work:
Added unit tests for functions that fit the neutron and nist the data.

#### To test:
Run the test files in the mantidpython console and check if the tests are successful (if tests with fail in their name do fail, that is considered expected behaviour).

### CODE REVIEW

**Comment by Anders-Markvardsen** [comment]
When `run FittingBenchmarkingGroupTest.py` I get:

```
======================================================================
FAIL: test_doFittingBenchmarkGroup_neutron_return_results_ENGINXpeak19_problem (__main__.FittingBenchmarkingGroup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Midlertiddig\fitbenchmarking\fitbenchmarking\test\FittingBenchmarkingGroupTest.py", line 421, in test_doFittingBenchmarkGroup_neutron_return_results_ENGINXpeak19_problem
    self.assertEqual(result_expected.fit_chi2, result.fit_chi2)
AssertionError: 0.7924313865920499 != 0.7924313865890911

======================================================================
FAIL: test_doFittingBenchmarkGroup_return_results_for_NIST_problems_Misra1a_Lanczos3_and_DanWood (__main__.FittingBenchmarkingGroup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Midlertiddig\fitbenchmarking\fitbenchmarking\test\FittingBenchmarkingGroupTest.py", line 355, in test_doFittingBenchmarkGroup_return_results_for_NIST_problems_Misra1a_Lanczos3_and_DanWood
    self.assertAlmostEqual(LANCresult2_expected.errors[1],result.errors[1])
AssertionError: 3219.9201499387495 != 3219.9201840764854 within 7 places

----------------------------------------------------------------------
Ran 3 tests in 7.271s

FAILED (failures=2)
An exception has occurred, use %tb to see the full traceback.

SystemExit: True

```

**Comment by bb511** [comment]
Issue should now be fixed.

**Comment by Anders-Markvardsen** [comment]
Other tests fail

```
======================================================================
FAIL: test_runFit_return_proper_parameters_for_neutron_problem_file_ENGINXpeak19 (__main__.FittingBenchmarkingOneProblem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Midlertiddig\fitbenchmarking\fitbenchmarking\test\FittingBenchmarkingOneProblemTest.py", line 284, in test_runFit_return_proper_parameters_for_neutron_problem_file_ENGINXpeak19
    self.assertEqual(chi2_expected, chi2)
AssertionError: 0.7924313865920499 != 0.7924313865890911

----------------------------------------------------------------------
Ran 15 tests in 5.597s

FAILED (failures=1)
An exception has occurred, use %tb to see the full traceback.

SystemExit: True
```

**Comment by Anders-Markvardsen** [comment]
```
======================================================================
FAIL: test_runFit_return_proper_parameters_for_neutron_problem_file_ENGINXpeak19 (__main__.FittingBenchmarkingOneProblem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Midlertiddig\fitbenchmarking\fitbenchmarking\test\FittingBenchmarkingOneProblemTest.py", line 285, in test_runFit_return_proper_parameters_for_neutron_problem_file_ENGINXpeak19
    self.assertListEqual(params_expected, params)
AssertionError: Lists differ: [-39.66490989383394, 0.0017093... != [-39.66490989421163, 0.0017093...

First differing element 0:
-39.6649098938
-39.6649098942
```

**Comment by Anders-Markvardsen** [comment]
```
======================================================================
FAIL: test_runFit_return_proper_parameters_for_neutron_problem_file_ENGINXpeak19 (__main__.FittingBenchmarkingOneProblem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Midlertiddig\fitbenchmarking\fitbenchmarking\test\FittingBenchmarkingOneProblemTest.py", line 288, in test_runFit_return_proper_parameters_for_neutron_problem_file_ENGINXpeak19
    self.assertTrue(result)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 15 tests in 5.318s

FAILED (failures=1)
An exception has occurred, use %tb to see the full traceback.

SystemExit: True
```

**Pull request merged**
