### PR TITLE
Remove fetch_data.py and test_fetch_data.py

### LINKED ISSUE #157: move parsing/fetch_data.py into utils
As of #156 fetch_data.py contain one method which is only used in utils/misc.py.

Delete fetch_data.py and test_fetch_data.py from parsing and move this code into where used, i.e. in utils

### PR DESCRIPTION
**Pull request by AtomAnu**
The function get_problem_files has been relocated to the file utils/misc.py

#### Description of Work

Fixes #157 

As the function get_problem_files in fetch_data.py is only used in utils/misc.py, I have now moved it to utils/misc.py instead.

#### Testing Instructions

1. Run `example_runScripts.py` and verify the results.

### CODE REVIEW

**Comment by Anders-Markvardsen** [comment]
Did you check if tests in test_fetch_data.py could be transferred in some form also?

**Comment by Anders-Markvardsen** [comment]
Please also resolve merge conflict thanks

**Comment by AtomAnu** [comment]
I should have added the test in `utils/misc.py`.

**Comment by AtomAnu** [comment]
I will look into the merge conflict.

**Comment by AtomAnu** [comment]
@Anders-Markvardsen 

I have completed it.

**Pull request merged**
