### PR TITLE
Issue #4: Enable multi-fit

### LINKED ISSUE #4: Update fit problem format to allow for testing against multiple datasets problems
Current FitBenchmarking only setup to fit one dataset against one model. This is umbrella issue to extend this to allow benchmarking of one model against multiple datasets where some fit parameters may be global to all datasets and others allowed to be different for individual datasets.

Currently a neutron_data fit problem is defined by the following name/value pairs:

```
name = 'ENGINX 193749 calibration, spectrum 651, peak 20'
input_file = 'ENGINX193749_calibration_spec651.nxs'
function = 'name=LinearBackground;name=BackToBackExponential,I=3527.31,A=1,B=0.05,X0=26185.9,S=29.4219'
fit_ranges = {'x': [26047.3026604, 26393.719109]}
description = ''
```

Change the following

* change fit_parameters to be called fit_properties, since they are properties of the fit, not parameters of a model
* change input_file to a comma separated list of files. Optionally allow each file to contain multiple datasets, e.g. spectra in a Nexus file. 

As an example, where two files the format could be:

```
input_files = ["fname1.txt", "fname2.txt"]
fit_ranges = [{'x': [1.0, 2.0]}, {'x': [2.3, 2.7]}]
```

The function need to be specifiable to specify if a parameter is global or not global, and in such a way that they can work easily with different minimizers in different software packages.

### PR DESCRIPTION
**Pull request by AndrewLister-STFC**
#### Description of Work

Fixes #4 

- [x] Allows mantid problems to be fit using mantids multi fit functionality.
- [x] Adds multi fit problem to try out 

Ideally this would be extended to allow other softwares to fit, although most do not offer the functionality for multi-fit out of the box, and mantids method for applying ties relies on adapting the cost function which is not compatible with other softwares.

#### Testing Instructions

1. Run a multi fit problem!!!!

Function: Does the change do what it's supposed to?
Tests: Does it pass? Is there adequate coverage for new code?
Style: Is the coding style consistent? Is anything overly confusing?
Documentation: Is there a suitable change to documentation for this change?

### CODE REVIEW

**Comment by AndrewLister-STFC** [comment]
Still need to do tests + docs.

**Comment by Anders-Markvardsen** [comment]
For information when running on windows currently I get (using Mantid 4.1.0)
```
C:\Midlertiddig\fitbenchmarking>python fitbenchmarking examples\benchmark_problems\MultiFit

Running the benchmarking on the Mantid MultiFit problem set

Unknown exception. Exiting.
No registered converter was able to produce a C++ rvalue of type double from this Python object of type numpy.ndarray
```
I wonder if this could have anything to do with the way I had to force fitbenchmarking to install in `C:\MantidInstall\bin\Lib\site-packages` using `C:\Midlertiddig\fitbenchmarking>c:\MantidInstall\bin\Scripts\pip.cmd install --target=C:\MantidInstall\bin\Lib\site-packages .`
@AndrewLister-STFC or @AnthonyLim23 can you see anything obvious.

**Comment by AndrewLister-STFC** [comment]
@Anders-Markvardsen Running with the `-d` option (for debug-mode) from the commandline should give a full traceback. I also notice you are not passing in an options file, Multi Fit only works with mantid so this will need to be specified to get any results. Perhaps this is an issue where a non-mantid solver is trying to run the problem?

**Comment by Anders-Markvardsen** [comment]
@AnthonyLim23 could you try to reproduce this on Windows (it should take you 2 minutes

* Install mantid nightly 
* start mantid notebook nightly
* in the jupyter browser select New -> Terminal
* cd to where you have downloaded fitbenchmarking
* try to install it using `..\..\MantidNightlyInstall\bin\Scripts\pip install fitbenchmarking` (where you may have to adjust the relative path depending on you have downloaded fitbenchmarking to. Note if you absolute path than for some irritating reason it open a separate terminal which self close)

I see the following error, just would like to know if this is something about my specific setup
```
PS C:\Midlertiddig\fitbenchmarking> ..\..\MantidNightlyInstall\bin\Scripts\pip install fitbenchmarking
Requirement already satisfied: fitbenchmarking in c:\midlertiddig\fitbenchmarking (0.1.dev2)
Requirement already satisfied: docutils in c:\mantidnightlyinstall\bin\lib\site-packages (from fitbench
marking) (0.15.2)
Collecting numpy<1.17 (from fitbenchmarking)
  Using cached https://files.pythonhosted.org/packages/b7/6f/24647f014eef9b67a24adfcbcd4f4928349b4a0f83
93b3d7fe648d4d2de3/numpy-1.16.6.zip
Collecting matplotlib<3.0 (from fitbenchmarking)
  Using cached https://files.pythonhosted.org/packages/85/77/d51e09efc5962f7013e9d2acc3fa40029487f29816
4bdaea5c8c4e91babe/matplotlib-2.2.5-cp38-cp38-win_amd64.whl
Collecting scipy<1.3,>=0.18 (from fitbenchmarking)
  Using cached https://files.pythonhosted.org/packages/62/4f/7e95c5000c411164d5ca6f55ac54cda5d200a3b671
9dafd215ee0bd61578/scipy-1.2.3.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\MantidNightlyInstall\bin\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0
] = '"'"'C:\\Users\\ajm64\\AppData\\Local\\Temp\\pip-install-_rmthvjm\\scipy\\setup.py'"'"'; __file__='
"'"'C:\\Users\\ajm64\\AppData\\Local\\Temp\\pip-install-_rmthvjm\\scipy\\setup.py'"'"';f=getattr(tokeni
ze, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(
compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\ajm64\AppData\Local\Temp\pip-install-_rmthvjm\scipy\
    Complete output (103 lines):
    Processing numpy/random\_bounded_integers.pxd.in
    Processing numpy/random\mtrand.pyx
    Traceback (most recent call last):
      File "C:\Users\ajm64\AppData\Local\Temp\easy_install-ggezua4v\numpy-1.18.1\tools\cythonize.py", l
ine 61, in process_pyx
        from Cython.Compiler.Version import version as cython_version
    ModuleNotFoundError: No module named 'Cython'
```

**Comment by Anders-Markvardsen** [comment]
@AndrewLister-STFC note running in debug get

```
C:\Midlertiddig\fitbenchmarking>fitbenchmarking -d examples\benchmark_problems\NIST\average_difficulty

Running the benchmarking on the NIST_average_difficulty problem set

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\fitbenchmarking\cli\exception_handler.py", line 25, in wrapped
    return f(*args, **kwargs)
  File "c:\python37\lib\site-packages\fitbenchmarking\cli\main.py", line 108, in run
    data_dir=data_dir)
  File "c:\python37\lib\site-packages\fitbenchmarking\core\fitting_benchmarking.py", line 47, in fitbenchmark_group
    parsed_problem = parse_problem_file(p, options)
  File "c:\python37\lib\site-packages\fitbenchmarking\utils\output_grabber.py", line 22, in __exit__
    self.stop()
  File "c:\python37\lib\site-packages\fitbenchmarking\utils\output_grabber.py", line 44, in stop
    self.origstream.flush()
OSError: [WinError 1] Incorrect function

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\Scripts\fitbenchmarking-script.py", line 11, in <module>
    load_entry_point('FitBenchmarking==0.1.dev2', 'console_scripts', 'fitbenchmarking')()
  File "c:\python37\lib\site-packages\fitbenchmarking\cli\main.py", line 153, in main
    run(problem_sets=args.problem_sets, options_file=args.options_file, debug=args.debug_mode)
  File "c:\python37\lib\site-packages\fitbenchmarking\cli\exception_handler.py", line 35, in wrapped
    print('Unknown exception. Exiting.')
OSError: [WinError 1] Incorrect function
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
OSError: [WinError 1] Incorrect function
```

**Comment by AndrewLister-STFC** [comment]
> 
> 
> @AndrewLister-STFC note running in debug get
> 
> ```
> C:\Midlertiddig\fitbenchmarking>fitbenchmarking -d examples\benchmark_problems\NIST\average_difficulty
> 
> Running the benchmarking on the NIST_average_difficulty problem set
> 
> Traceback (most recent call last):
>   File "c:\python37\lib\site-packages\fitbenchmarking\cli\exception_handler.py", line 25, in wrapped
>     return f(*args, **kwargs)
>   File "c:\python37\lib\site-packages\fitbenchmarking\cli\main.py", line 108, in run
>     data_dir=data_dir)
>   File "c:\python37\lib\site-packages\fitbenchmarking\core\fitting_benchmarking.py", line 47, in fitbenchmark_group
>     parsed_problem = parse_problem_file(p, options)
>   File "c:\python37\lib\site-packages\fitbenchmarking\utils\output_grabber.py", line 22, in __exit__
>     self.stop()
>   File "c:\python37\lib\site-packages\fitbenchmarking\utils\output_grabber.py", line 44, in stop
>     self.origstream.flush()
> OSError: [WinError 1] Incorrect function
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Python37\Scripts\fitbenchmarking-script.py", line 11, in <module>
>     load_entry_point('FitBenchmarking==0.1.dev2', 'console_scripts', 'fitbenchmarking')()
>   File "c:\python37\lib\site-packages\fitbenchmarking\cli\main.py", line 153, in main
>     run(problem_sets=args.problem_sets, options_file=args.options_file, debug=args.debug_mode)
>   File "c:\python37\lib\site-packages\fitbenchmarking\cli\exception_handler.py", line 35, in wrapped
>     print('Unknown exception. Exiting.')
> OSError: [WinError 1] Incorrect function
> Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
> OSError: [WinError 1] Incorrect function
> ```

Hi @Anders-Markvardsen, it looks like you're running this branch with python3. But I don't think the latest python3 update branch has been merged yet. Additionally this is the same issue you got earlier where the OutputGrabber was failing on windows, perhaps you could test this using wsl for now and raise an issue to cover the new bug (Windows outputGrabber flush)?

**Comment by Anders-Markvardsen** [comment]
Thanks Andrew. May this also explains why I see similar ish error with 213-py3_switchover?

**Comment by AndrewLister-STFC** [comment]
> 
> 
> Thanks Andrew. May this also explains why I see similar ish error with 213-py3_switchover?

Yes, I expect they're both caused by the same issue

**Comment by Anders-Markvardsen** [comment]
small decrease in coverage acceptable

**Pull request merged**
