### PR TITLE
Cost function linting fixes

### LINKED ISSUE #766: Fix linting in cost-functions
Fix the cost function subdirectory - related to #702

Bring the errors and warnings down to zero, and address others if appropriate.

### PR DESCRIPTION
**Pull request by tyronerees**
#### Description of Work

Fixes #766 

There are still some warnings:
```
************* Module fitbenchmarking.cost_func.poisson_cost_func
cost_func/poisson_cost_func.py:33:4: W0235: Useless super delegation in method '__init__' (useless-super-delegation)
************* Module fitbenchmarking.cost_func.tests.test_cost_func
cost_func/tests/test_cost_func.py:256:8: W0201: Attribute 'options' defined outside __init__ (attribute-defined-outside-init)
```
that may or may not be easy to fix...?

#### Testing Instructions

1. run flake8, pylint on code
2. check changes don't break anything
3.

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

### CODE REVIEW

**Comment by AndrewLister-STFC** [comment]
The remaining issues make sense and can probably be fixed:
- Useless super is telling us that the init for the poisson class in unnecessary as thats exactly what happens automatically so we should remove it.
- Attribute options defined outside init is on purpose since unittest uses a setup function rather than an init -- we can probably just disable this at the top of the test file

**Review by AndrewLister-STFC — CHANGES_REQUESTED** [review]
Sorry for the delay in reviewing... I got this confused with the umbrella linting PR.

I'm still getting a few linting errors from pylint that should be quick to fix:
- R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
- fitbenchmarking/cost_func/nlls_base_cost_func.py:7:0: C0411: third party import "from numpy import dot" should be placed before "from fitbenchmarking.cost_func.base_cost_func import CostFunc" (wrong-import-order)
- fitbenchmarking/cost_func/cost_func_factory.py:29:8: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)

**Comment by tyronerees** [comment]
pytest and flake8 now run cleanly on my system.  I still can't replicate the additional linting errors you found, although I think I wrote down the wrong pylint version -- I've tested with the version installed on GitHub actions (6.2.2), and it returns cleanly now (except for a refactor suggestion)

**Comment by AndrewLister-STFC** [comment]
> 
> 
> pytest and flake8 now run cleanly on my system. I still can't replicate the additional linting errors you found, although I think I wrote down the wrong pylint version -- I've tested with the version installed on GitHub actions (6.2.2), and it returns cleanly now (except for a refactor suggestion)

I think pylint is running 2.8.2 on github actions, I think you must have been looking at pytest?

**Comment by tyronerees** [comment]
Should be fixed now!  Only a couple of refactor suggestions left for me on pylint 2.8.2.

**Review by AndrewLister-STFC — APPROVED** [review]

**Pull request merged**
