### PR TITLE
Added the precommit autoupdate workflow using the GitHub Actions bot

### LINKED ISSUE #1390: Add a pre-commit autoupdate GitHub workflow
Automate the update of the precommit hook.

### PR DESCRIPTION
**Pull request by RabiyaF**
## Description of work

Fixes #1390 

## Testing Instructions

I tested this on a private repo to make sure that the PR was being created correctly. I did however had to make sure that the GitHub-actions[bot] had write permissions on the repo. There wouldn't be an easy way to test it expect merging and running the workflow and making sure that the branch protection rules allow for PRs to be created.

image

## Checklist

- [x] The title is of a format appropriate for a line in future release notes.
- [x] I have added the appropriate tags to the PR.
- [x] My PR represents one logical piece of work.
- [x] My PR fully fixes the issue linked. If new issues have been created, what are they?
- [x] I have added the appropriate tests to cover code that has been added.
- [x] I have updated the documentation in the relevant places to cover the changes.

### CODE REVIEW

**Review by AndrewLister-STFC — APPROVED** [review]
All looks good on paper 🚀

**Comment by RabiyaF** [comment]
https://pre-commit.ci

I am looking into something else as well. Mantid uses this in their [repository](https://github.com/mantidproject/mantid/blob/main/.pre-commit-config.yaml). I just thought that using GitHub might be a better way of doing this rather than using something third party. Would you mind holding up on merging this till I get an opportunity to test this. The precommit-ci might be more straightforward way of doing it.

**Comment by RabiyaF** [comment]
I added fitbenchmarking to this pre-commit.ci.
Screenshot 2024-11-25 at 17 41 50

Let's see if it creates a PR on the repo in a few weeks when something is updated. I am not sure what is better though 🤷🏼‍♀️ It seems like a shady website and we will not have control over the updates timings. I setup this workflow to run at the same time as our other schedule tasks. 

image

**Comment by RabiyaF** [comment]
I will close this PR in favour of using precommit.ci like the Mantid Repo. Incase there are issues we can always return to this workflow.

**Pull request closed without merging**
