### PR TITLE
238 pep8

### PR DESCRIPTION
**Pull request by arm61**
#### Description of Work

Improving PEP8 compliance

#### Testing Instructions

1. run flake8, pylint and test framework

### CODE REVIEW

**Comment by AndrewLister-STFC** [comment]
Testing against mantid to check Travis: Script succeeded on my machine.

It looks like travis had issues in the mantid install previous to the test run, you can see it if you expand the line:
```
mantidpython -m mantid.simpleapi || true
```

**Comment by AndrewLister-STFC** [comment]
> Testing against mantid to check Travis: Script succeeded on my machine.
> It looks like travis had issues in the mantid install previous to the test run, you can see it if you expand the line:
> mantidpython -m mantid.simpleapi || true

I found on other PRs that it looks like this fails when theres a merge conflict as Travis relies on merging before running

**Comment by arm61** [comment]
@AndrewLister-STFC rebasing doesn't appear to fix the travis issues

**Comment by Anders-Markvardsen** [comment]
@arm61 note #207 has just been merged to master hence with uploading this branch it should aligned with master. 

Also would it be OK to change the title to something like "Improving PEP8 compliance for ...", where ... is some specific module or file of the code, i.e. this PR is one step towards the holly grail of pep8 complience

**Comment by arm61** [comment]
just saying that this is on my radar (just a bit mad today and tomorrow)

**Comment by arm61** [comment]
will make a new PR for each bit individually!

**Pull request closed without merging**
