### PR TITLE
Issue #682: Move to GitHub Actions; Travis stopped supporting open source

### LINKED ISSUE #682: Replicate travis-ci linux (and mac) build on azure pipeline
With travis-ci possible reaching end of the line, this labelled with high priority

### PR DESCRIPTION
**Pull request by AndrewLister-STFC**
#### Description of Work
With Travis no longer supporting open source, this PR switches to Azure for all testing.

Fixes #682

#### Testing Instructions

1. Do tests run?
2. Do tests match?

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

### CODE REVIEW

**Comment by AndrewLister-STFC** [comment]
Need to get coveralls working now

**Comment by AndrewLister-STFC** [comment]
I think I've got coveralls working!
When reviewing please *DO NOT* merge yet, we need to remove the travis links. I've left them in for now to allow comparison.

**Review by tyronerees — DISMISSED** [review]
All tests now passing, and we know they fail on failure.  

I like the Azure->GitHub interface -- it makes it easy to see what the status is.  

I think this is ready to merge

**Comment by AndrewLister-STFC** [comment]
I just need to add a schedule to the yaml to enable automatic runs.

**Comment by AndrewLister-STFC** [comment]
@tyronerees To get coveralls working I had to switch to github actions. Installing had some problems as setuptools_scm couldn't find a version, this was fixed by providing a backup (set to 1.0.0) as mentioned [here](https://github.com/cloud-custodian/cloud-custodian/issues/5283#issuecomment-579276511).

**Review by tyronerees — APPROVED** [review]
All seems good to me :-)

**Pull request merged**
