### PR TITLE
Webpage buttons

### LINKED ISSUE #674: Make results web page buttons display better on Windows
**To reproduce**
On Windows install and type and run `fitbenchmarking` and observe e.g. the page

image

Make the buttons (and possibly other stuff) on this page look more like that you get when running on Linux.

### PR DESCRIPTION
**Pull request by wathen**
#### Description of Work

Fixes #674 

Copies the fonts directory into the results directory

#### Testing Instructions

1. Check the buttons on the index pages work

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

### CODE REVIEW

**Review by jfowkes — APPROVED** [review]
I can confirm this fixes #674 on Mac.

**Comment by Anders-Markvardsen** [comment]
On windows 10 machine observe now:

image

and button icons displayed

**Review by Anders-Markvardsen — APPROVED** [review]
Tested on Windows and code changes clear

**Comment by Anders-Markvardsen** [comment]
and back ported into release-0.1.x

**Pull request merged**
