### PR TITLE
Table refactoring

### LINKED ISSUE #431: Refactor table generation
Currently the ``controllers`` and ``parsers`` are setup using classes to ease extending FitBenchmarking. Whilst the table generation is concise, it should be done using classes to enable users and contributes a clear and usable way to add additional tables.

### LINKED ISSUE #463: results_processing/tests/test_tables tests
Placeholder needs filling in.

### PR DESCRIPTION
**Pull request by wathen**
#### Description of Work
Fixes #431  
FIxes #463

Refactor tables to use a factory classes similar to the parsers and the controllers

#### Testing Instructions

1. Check tables are the same and are understandable

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

### CODE REVIEW

**Comment by wathen** [comment]
I'm going to look over the PEP8 requirements on Monday morning but otherwise this is ready to be reviewed

**Comment by wathen** [comment]
@Anders-Markvardsen and @tyronerees, this should be ready for you to a look at it now

**Comment by Anders-Markvardsen** [comment]
Perhaps unrelated to this PR, when building doc locally on Ubuntu from WSL Windows 10 I get a lot of complains for `LaTeX Error: File anyfontsize.sty not found.` Anyone else see this?

**Comment by Anders-Markvardsen** [comment]
Unrelated to this PR I believe I get

```
ajm64@NDLT1118:~/fitbenchmarking$ fitbenchmarking
In /home/ajm64/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The text.latex.unicode rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2.
In /home/ajm64/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In /home/ajm64/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The pgf.debug rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2.
In /home/ajm64/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The verbose.level rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In /home/ajm64/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The verbose.fileo rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
usage: FitBenchmarking [-h] [-o OPTIONS_FILE] [-d]
                       problem_sets [problem_sets ...]
```

Do we have any issue for capturing 3rd party packages warnings and / or deprecation messages?

**Comment by wathen** [comment]
> Perhaps unrelated to this PR, when building doc locally on Ubuntu from WSL Windows 10 I get a lot of complains for `LaTeX Error: File anyfontsize.sty not found.` Anyone else see this?

No I don't seem to get this error

**Pull request merged**
