### PR TITLE
Enable CT for release branch

### LINKED ISSUE #574: Enable CT for release branch
**Is your feature request related to a problem? Please describe.**
New git workflow doesn't have CT on release branch by default.

**Describe the solution you'd like**
- Use whitelisting of master and release branches (with regex) so that only these branches are built by Travis.
- Enable build on push for Travis

### PR DESCRIPTION
**Pull request by TOFarmer**
#### Description of Work
- Added whitelist to .travis.yml with master and a regex for all release branches (matches anything starting with "release-"
- Added notifications to fitbenchmarking slack channel (build-failures)

Two notes:
- I realised that adding a badge might not be practical, as it would need to continually be updated to point at the latest release to be of any use.

If you have any thoughts on these then please let me know.

**NB: To complete this PR, Travis has had "Build on push" enabled in the settings.  I think that because other branches will not have a whitelist in .travis.yml, they will build on every push, which is not desired.  Therefore I recommend that, after this PR is merged, every current branch should have master merged as a priority, to stop a lot of unnecessary builds.**

Fixes #574 

#### Testing Instructions

1. The only practical test will be when this is merged to master (a push build on master should appear on Travis) and then again when it is cherry-picked to the release (again, push build on Travis).
2. Other than this, if you wanted to be sure that the slack notification was working, after merging you could either:
- add a commit to master or release which breaks the build and see if slack gets a notification,
- or temporarily change the slack notification conditions to `success: always`

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

### CODE REVIEW

**Comment by TOFarmer** [comment]
@wathen @tyronerees @Anders-Markvardsen 
Realised that while I suggested that one person should receive build failures to their email, we didn't actually determine who this should be.  Also I don't think it is possible for them to only get release failures rather than master and release failures, so:
- Either we leave it so that only support@fitbenchmarking.com gets notifications,
- Or support and one person get all notifications
- Or we support and one person only get notifications for release (i.e. no email notifications for master)

**Comment by wathen** [comment]
> @wathen @tyronerees @Anders-Markvardsen
> Realised that while I suggested that one person should receive build failures to their email, we didn't actually determine who this should be. Also I don't think it is possible for them to only get release failures rather than master and release failures, so:
> 
>     * Either we leave it so that only [support@fitbenchmarking.com](mailto:support@fitbenchmarking.com) gets notifications,
> 
>     * Or support and one person get all notifications
> 
>     * Or we support and one person only get notifications for release (i.e. no email notifications for master)

I talked to Tyrone this morning we think its probably best if you put me down to receive the notifications. If its possible we should also send the notifications to the gmail email too.

**Comment by TOFarmer** [comment]
> I talked to Tyrone this morning we think its probably best if you put me down to receive the notifications. If its possible we should also send the notifications to the gmail email too.

Will do - could you please remind me of the gmail email?

**Comment by wathen** [comment]
> > I talked to Tyrone this morning we think its probably best if you put me down to receive the notifications. If its possible we should also send the notifications to the gmail email too.
> 
> Will do - could you please remind me of the gmail email?

Oh I just meant to the fitbenchmarking address (**support@fitbenchmarking.com**) as well as my STFC one.

**Comment by TOFarmer** [comment]
Ok, I've added your STFC email.  So you and support@fitbenchmarking.com will get emails on failure of either master or any release branch.

**Pull request merged**
