### PR TITLE
JUnit Publish github action test results

### LINKED ISSUE #964: Add JUnit Publish action to create test results comments
Add something based on this to improve test feedback: https://github.com/marketplace/actions/publish-unit-test-results

### PR DESCRIPTION
**Pull request by robertapplin**
#### Description of Work
This PR attempts to publish the test results using the JUnit Publish github action. This aims to make the test results more readable and quicker to fix in the future.

Fixes #964

#### Testing Instructions

1.
2.
3.

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

### CODE REVIEW

**Comment by robertapplin** [comment]
This is what the output looks like when a test fails [this](https://github.com/fitbenchmarking/fitbenchmarking/runs/4432112325)

**Comment by AndrewLister-STFC** [comment]
@robertapplin Did you say windows couldn't be added because of filename clashes?

**Comment by robertapplin** [comment]
> @robertapplin Did you say windows couldn't be added because of filename clashes?

Yes, I think it wouldn't work because both the windows and linux workflow call the same `.sh` file, and this will create a junit xml file with the same name. Maybe it is possible to pass in a unique name to the `.sh` file?

**Comment by AndrewLister-STFC** [comment]
> > @robertapplin Did you say windows couldn't be added because of filename clashes?
> 
> Yes, I think it wouldn't work because both the windows and linux workflow call the same `.sh` file, and this will create a junit xml file with the same name. Maybe it is possible to pass in a unique name to the `.sh` file?

That's fine, usually if windows fails so does linux, and if not it's probably an install issue

**Review by AndrewLister-STFC — APPROVED** [review]

**Pull request merged**
