### PR TITLE
use mathjax for maths in results pages

### LINKED ISSUE #683: Use mathjax for the math fonts in the results pages
The results pages currently don't use the best maths formatting on some systems.  We should switch the interpreter to use MathJax to get around this problem.

### PR DESCRIPTION
**Pull request by tyronerees**
#### Description of Work

Fixes #683 -- instead of looking like this:
image
equations should now look like:
image

#### Testing Instructions

1.  Run fitbenchmarking, ensure the equations in the results pages look good
2.  Run fitbenchmarking without being connected to the internet -- do they look the same?

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

### CODE REVIEW

**Comment by tyronerees** [comment]
I took everything out and only added back in the files the browser complained it couldn't find.  It turns out that all that seems to be missing (aside from the js file called) is a couple of fonts, which I've left in.

**Review by jfowkes — CHANGES_REQUESTED** [review]
Looks great! Works perfectly for me except for two minor issues:

1. The maths under local_min table hasn't ben rendered in MathJax as it's <class='formula'> rather than <classs='math'>:
Screenshot 2020-12-01 at 1 46 21 pm

2. I'm seeing a weird artifact on my system in the i in min (this could just be a safari bug):
Screenshot 2020-12-01 at 1 45 53 pm

**Comment by jfowkes** [comment]
Regarding 2. above, it could also be a missing font that is being substituted. MathJax complains about not being able to load the following latex fonts (clearly some of these, like Fraktur, we never actually use): 
```
fitbenchmarking_results/js/output/chtml/fonts/woff-v2/MathJax_Main-Bold.woff
fitbenchmarking_results/js/output/chtml/fonts/woff-v2/MathJax_Main-Italic.woff
fitbenchmarking_results/js/output/chtml/fonts/woff-v2/MathJax_Math-BoldItalic.woff
fitbenchmarking_results/js/output/chtml/fonts/woff-v2/MathJax_Size1-Regular.woff
fitbenchmarking_results/js/output/chtml/fonts/woff-v2/MathJax_Size4-Regular.woff
fitbenchmarking_results/js/output/chtml/fonts/woff-v2/MathJax_AMS-Regular.woff
fitbenchmarking_results/js/output/chtml/fonts/woff-v2/MathJax_Calligraphic-Regular.woff
fitbenchmarking_results/js/output/chtml/fonts/woff-v2/MathJax_Calligraphic-Bold.woff
fitbenchmarking_results/js/output/chtml/fonts/woff-v2/MathJax_Fraktur-Regular.woff
fitbenchmarking_results/js/output/chtml/fonts/woff-v2/MathJax_Fraktur-Bold.woff
fitbenchmarking_results/js/output/chtml/fonts/woff-v2/MathJax_SansSerif-Regular.woff
fitbenchmarking_results/js/output/chtml/fonts/woff-v2/MathJax_SansSerif-Bold.woff
fitbenchmarking_results/js/output/chtml/fonts/woff-v2/MathJax_SansSerif-Italic.woff
fitbenchmarking_results/js/output/chtml/fonts/woff-v2/MathJax_Script-Regular.woff
fitbenchmarking_results/js/output/chtml/fonts/woff-v2/MathJax_Typewriter-Regular.woff
fitbenchmarking_results/js/output/chtml/fonts/woff-v2/MathJax_Vector-Regular.woff
fitbenchmarking_results/js/output/chtml/fonts/woff-v2/MathJax_Vector-Bold.woff
```

**Comment by jfowkes** [comment]
Just tested with the MathJax CDN and I'm still seeing 2. so clearly none of the above listed fonts are actually required, must therefore be a bug in Safari. Happy to approve once 1. is fixed.

**Review by jfowkes — APPROVED** [review]
Excellent thanks, works perfectly for me. Approving.

**Pull request merged**
