### PR TITLE
Azure test incorrect report

### LINKED ISSUE #595: Azure test incorrect report
**Description of the error**
The Windows tests in Azure say they pass when they actually fail.
failed_tests

**Describe the expected result**
Azure correctly reports passes and fails

### PR DESCRIPTION
**Pull request by Anders-Markvardsen**
#### Description of Work

Fixes #595 

Corrects reports successes and failures for the window tests in azure.

#### Testing Instructions

1. Check that the tests correctly pass on azure
2. Check (via previous commits) that azure reports failures correctly

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

### CODE REVIEW

**Comment by Anders-Markvardsen** [comment]
Windows build fails on python 3.6 with error on `import mock` which makes sense since mock refer to pre python 3.3 and from python 3.3 onward unittest.mock available, and external mock not included requirements.txt. @wathen what am I missing, how come line line 9 of `core/tests/test_fitting_benchmarking_benchmark.py` is `import mock` works on linux builds. Separately how come mock used and not unittest.mock?

**Comment by wathen** [comment]
> Windows build fails on python 3.6 with error on `import mock` which makes sense since mock refer to pre python 3.3 and from python 3.3 onward unittest.mock available, and external mock not included requirements.txt. @wathen what am I missing, how come line line 9 of `core/tests/test_fitting_benchmarking_benchmark.py` is `import mock` works on linux builds. Separately how come mock used and not unittest.mock?

Hmm, I'm not sure why but if `unittest.mock` works the same as `mock` then we might as well just use that instead?

**Comment by Anders-Markvardsen** [comment]
@wathen thanks and looks good with the changes. Separate to this PR I wondering if we should create a follow up issue to investigate the small differences in output, e.g. these are for all_parsers.txt:

```
                                bumps                    dfo                 minuit                     scipy             scipy_ls
                               amoeba                  dfogn                 minuit               Nelder-Mead      lm-scipy-no-jac
cubic, Start 1  1.119e-14 (2.899e+07)  5.244e-14 (1.358e+08)  3.586e-11 (9.288e+10)  6.267e-05 (1.623e+17)[1]        3.861e-22 (1)
cubic, Start 2  1.146e-14 (2.969e+07)  2.424e-17 (6.278e+04)  7.579e-06 (1.963e+16)     7.176e-11 (1.859e+11)        3.861e-22 (1)
Problem Def 1   6.784e+05 (5.225e+15)          1.299e-10 (1)       4.214e-07 (3245)      3.837e-09 (29.55)[1]  0.03966 (3.055e+08)

                                bumps                    dfo                 minuit                     scipy             scipy_ls
                               amoeba                  dfogn                 minuit               Nelder-Mead      lm-scipy-no-jac
cubic, Start 1  1.119e-14 (2.899e+07)  7.196e-14 (1.864e+08)  2.352e-07 (6.091e+14)  6.267e-05 (1.623e+17)[1]        3.861e-22 (1)
cubic, Start 2  1.146e-14 (2.969e+07)  1.312e-14 (3.397e+07)  7.579e-06 (1.963e+16)     7.176e-11 (1.859e+11)        3.861e-22 (1)
Problem Def 1   6.784e+05 (5.225e+15)          1.299e-10 (1)       4.214e-07 (3245)      3.837e-09 (29.55)[1]  0.03966 (3.055e+08)

```

Maybe we can briefly discuss in out weekly fitbenchmarking catch up tomorrow

**Review by tyronerees — APPROVED** [review]
All looks good -- well done in finding the issues!

I've created an issue to look at the differences in output

**Pull request merged**
