### PR TITLE
Extend algorithm type

### LINKED ISSUE #782: Add minimizer tags and more mathematical detail
Add tags for minimizers (e.g. LM, Nelder-Mead, etc) allowing users to compare similar methods across fitting software. Include information about which algorithm types are useful for particular purposes.

### PR DESCRIPTION
**Pull request by jess-farmer**
#### Description of Work

Fixes #782 

#### Testing Instructions

1. Check that new algorithm type options make sense, should any be added/removed?
2. Run fitbenchmarking with various algorithm type options and ensure that algorithm type is displayed as a tooltip when hovering over minimizer name in results tables

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

### CODE REVIEW

**Comment by jfowkes** [comment]
Looks great to me! While there can be a subtle distinction between Levenberg-Marquardt and Trust-Region algorithms (namely the strategy of how the lambda/trust-region radius is updated) that is far too subtle for any of our users.

Minor typo: in fitting_options.rst: simplect -> simplex

**Comment by jess-farmer** [comment]
Thanks for looking through this @jfowkes - good spot with the typo, I've now fixed that!

**Comment by tyronerees** [comment]
Just to pick up on what Jari says -- RALFit's `gn` and `gn_reg` are really Levenberg-Marquardt algorithms, so should probably be lumped in to that tag too.

**Review by jfowkes — CHANGES_REQUESTED** [review]
Looks great, aside from the warning message details:

```
        Software: SCIPY
            Minimizer: CG
Minimizer cannot be run with Controller with current "algorithm_type" option set.
Details: The minimizer selected, CG, is not within algorithm_check[options.algorithm_type] = [[]]
```
Would it be possible to make these messages more user-friendly? It's not clear from this it's trying to tell me there are no algorithms my chosen type available.

**Comment by jess-farmer** [comment]
@jfowkes yeah I see what you mean, that warning message isn't very clear! I have now changed it so that it is hopefully more user friendly!

**Review by jfowkes — APPROVED** [review]
Looks great, many thanks!

**Pull request merged**
