### PR TITLE
fix options_template and add tests for usage examples

### LINKED ISSUE #773: FitBenchmarking --help example not working
**Description of the error**

Running `fitbenchmarking --help` tells users:

```
usage: FitBenchmarking [-h] [-o OPTIONS_FILE]
                       [-p PROBLEM_SETS [PROBLEM_SETS ...]] [-d]

optional arguments:
  -h, --help            show this help message and exit
  -o OPTIONS_FILE, --options-file OPTIONS_FILE
                        The path to a FitBenchmarking options file
  -p PROBLEM_SETS [PROBLEM_SETS ...], --problem_sets PROBLEM_SETS [PROBLEM_SETS ...]
                        Paths to directories containing problem sets.
  -d, --debug-mode      Enable debug mode (prints traceback)

Usage Examples:

    $ fitbenchmarking
    $ fitbenchmarking -p examples/benchmark_problems/NIST/*
    $ fitbenchmarking -o examples/options_template.ini     -p examples/benchmark_problems/simple_tests     examples/benchmark_problems/Muon
```

However when running `fitbenchmarking -o examples/options_template.ini     -p examples/benchmark_problems/simple_tests` then get error:

```
Error while running FitBenchmarking. Exiting. See below for more information.
Failed to process options.
Details: The option 'external_output: no' in the ini file is invalid. external_output must be on or more of ['debug', 'display', 'log_only']
```

**To fix**
Two things:

* change `external_output` to be the default and with explanation of other values or reference to where get info of what `external_output` is
* add CI test for the examples we currently provide to users. Suggest a test where strip out the examples from `fitbenchmarking --help` and run these; preferably checking the output returned, but as a minimum that the examples run without bailing out

### LINKED ISSUE #774: Reconsider examples provided via fitbenchmarking --help
**Is your feature request related to a problem? Please describe.**
Reconsider the examples that comes with `fitbenchmarking --help`

```
Usage Examples:

    $ fitbenchmarking
    $ fitbenchmarking -p examples/benchmark_problems/NIST/*
    $ fitbenchmarking -o examples/options_template.ini     -p examples/benchmark_problems/simple_tests     examples/benchmark_problems/Muon
```

Discussion points / suggestions for fixes:

* When running fitbenchmarking as `fitbenchmarking`, i.e. without arguments. Add doc to inform the user up front what is then run
* For all examples give an estimate of how long they can expect any of the examples to run on a standard PC (whatever, e.g. mine is Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz, 3096 Mhz, 4 Core(s), and 16 GB or ram). That way the user can pick the fastest to run first say and then go on from there
* I haven't looked in detail but running `fitbenchmarking` with no arguments appears to be the same as `fitbenchmarking -p examples/benchmark_problems/NIST/*`
  * ensure no two examples are the same
  * consider changing runing `fitbenchmarking` with no arguments to running just the examples `-p examples/benchmark_problems/NIST/average_difficulty` or similar, and example that on a standard PC will complete within a minute

### PR DESCRIPTION
**Pull request by jess-farmer**
#### Description of Work

Fixes #773, fixes #774

#### Testing Instructions

1. Check that all usage examples now run without errors
2. Check that test for usage examples passes
3.

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

### CODE REVIEW

**Comment by tyronerees** [comment]
@Anders-Markvardsen -- could you please take a look at this PR?

**Comment by Anders-Markvardsen** [comment]
What I observe. Running `fitbenchmarking -o examples/options_template.ini -p examples/benchmark_problems/simple_tests` no longer return `ini file is invalid` and works.

When running `fitbenchmarking` now inform which problem definition files are run, which is `NIST_average_difficulty problem set` and run faster the previous default and is better.

Looks good. However now with #773 fixed observe the following. Output from `fitbenchmarking --help` include

```
Usage Examples:

    $ fitbenchmarking
    $ fitbenchmarking -p examples/benchmark_problems/NIST/*
    $ fitbenchmarking -o examples/options_template.ini     -p examples/benchmark_problems/simple_tests     examples/benchmark_problems/Muon
```

when running `fitbenchmarking -o examples/options_template.ini     -p examples/benchmark_problems/simple_tests` observe output include

```
Running the benchmarking on the simple_tests problem set

######################################
 Running data from: cubic-fb.txt 1/15
######################################
Missing dependencies for fit.
Details: Requirements are missing for mantid parser: No module named 'mantid'
```

Mantid is not installed by default. Could --help examples be picked with only use minimizers which we have installed by default? Or (and I think less preferable) include comment to tell user up front that running this example require external software installed first.

**Comment by jess-farmer** [comment]
Thank you @Anders-Markvardsen for looking through this - that's a really good point about not using external software for the help examples, I've now updated the final example so that only default software is required to run it.

**Comment by Anders-Markvardsen** [comment]
Thanks for these changes. When I run  `fitbenchmarking --help` example `fitbenchmarking -o examples/options_template.ini -p examples/benchmark_problems/simple_tests examples/benchmark_problems/Muon`  it still complains Mantid need to be installed. Do you see the same?

**Comment by jess-farmer** [comment]
Hmm, so following my changes that example should not come up any more when `fitbenchmarking --help` is called. For me the usage examples I see when calling `fitbenchmarking --help` are:

```
Usage Examples:

    $ fitbenchmarking
    $ fitbenchmarking -p examples/benchmark_problems/NIST/*
    $ fitbenchmarking -o examples/options_template.ini     -p examples/benchmark_problems/CUTEst     examples/benchmark_problems/NIST/low_difficulty

    Runtimes for these usage examples are approximately 75, 200 and 90 seconds respectively (on an i7 core laptop with 32GB RAM) 
```
none of which require any external software to be installed. Not sure why you are still seeing the other example, I'm guessing the branch is up to date etc?

**Comment by Anders-Markvardsen** [comment]
@jess-farmer you were right I hadn't uninstalled/installed properly. Now observe `fitbenchmarking --help` as you see above. However, when I run it (again using a clean install using `pip install .` on a clean virtual env) I observe

```
(venv_fitbenchmarking) anders@NDLT1118:~/fitbenchmarking$ fitbenchmarking -o examples/options_template.ini     -p examples/benchmark_problems/CUTEst     examples/benchmark_problems/NIST/low_difficulty
Running the benchmarking on the CUTEst problem set

#####################################
 Running data from: PALMER6C.dat 1/5
#####################################
    Starting value: 1/1
        Software: BUMPS
Error while running FitBenchmarking. Exiting. See below for more information.
Missing dependencies for fit.
Details: Requirements are missing for the bumps controller: No module named 'bumps'
``` 

Do you see the same?

**Comment by jess-farmer** [comment]
Yes, this is a good point - bumps is a default fitting software in the sense that it is pip installable but not automatically installed when a user installs fitbenchmarking. I think the only fitting software that is truly 'default' is scipy, so we could take out all other fitting options from `options_template.ini` but I think it would be a shame to restrict all usage examples to only scipy.

In the docs, the installation instructions do encourage users to also install any fitting software that is pip installable
Screenshot 2021-07-01 165201
so I think including software on this list shouldn't be too much of a problem. I could always add some detail to the error message pointing users to the installation docs page in case a user isn't aware of how to install the required software - what do you think?

**Comment by Anders-Markvardsen** [comment]
I like your last suggestion putting in a comment just above or below the listed --help examples saying something like "The last listed example assumes fitbenchmarking has been installed using python -m pip install fitbenchmarking[bumps, ..], see the install instructions" or "The last listed example assumes fitbenchmarking has been installed with a number of other easily installable fitting software packages including bumps, see the install instructions" or something to that effect. What do you think? Thanks

**Review by Anders-Markvardsen — APPROVED** [review]
Manually tested. Code and comments looks good

**Pull request merged**
