### PR TITLE
Issue #222: Set auto width on html tables

### LINKED ISSUE #222: Review column formatting
As observed in #220, the width of the first column containing the names of the data sets is much longer than necessary.

### PR DESCRIPTION
**Pull request by AndrewLister-STFC**
#### Description of Work

Fixes #222

Adds title to html tables and sets the size of columns in the html table to auto.

#### Testing Instructions

1. Run fitbenchmarking with only 1 minimizer
2. Compare resulting table with master

Function: Does the change do what it's supposed to?

Tests: Does it pass? Is there adequate coverage for new code?

Style: Is the coding style consistent? Is anything overly confusing?

Documentation: Is there a suitable change to documentation for this change?

### CODE REVIEW

**Comment by wathen** [comment]
Auto formatting the columns in the table of results changes the size of all the columns, see below. Personally I don't think this is a problem. What do you think @tyronerees and @Anders-Markvardsen?

Auto_format_table

**Comment by tyronerees** [comment]
This fails for me: 
```
Producing output for the short_neutron problem set

<string>:3: (ERROR/3) Error in "table" directive:
unknown option: "widths".

.. table:: FitBenchmarking Results
   :widths: auto

   +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+
   |                                                                                                                                                                                                                   |BFGS                                     |Conjugate gradient (Fletcher-Reeves imp.)|Conjugate gradient (Polak-Ribiere imp.)  |Damped GaussNewton                       |Levenberg-Marquardt                      |Levenberg-MarquardtMD                    |Simplex                                  |SteepestDescent                          |Trust Region                             |
   +===================================================================================================================================================================================================================+=========================================+=========================================+=========================================+=========================================+=========================================+=========================================+=========================================+=========================================+=========================================+
   |`ENGINX 193749 calibration, spectrum 651, peak 19 1 </home/dgk98065/fitbenchmarking/results/short_neutron/support_pages/short_neutron_enginx_193749_calibration_spectrum_651_peak_19_1.html>`__                    | :ranking-top-1:`388.4 (1.005)`          | :ranking-top-1:`390.6 (1.011)`          | :ranking-top-1:`391 (1.012)`            | :ranking-low-5:`inf (inf)`              | :ranking-top-1:`388.8 (1.006)`          | :ranking-top-1:`388.9 (1.006)`          | :ranking-top-1:`421.1 (1.089)`          | :ranking-med-3:`518.8 (1.342)`          | :ranking-top-1:`386.6 (1)`              |
   +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+
   |`WISH17701 panel 103 tube 3 calibration, peak 1 1 </home/dgk98065/fitbenchmarking/results/short_neutron/support_pages/short_neutron_wish17701_panel_103_tube_3_calibration_peak_1_1.html>`__                       | :ranking-low-5:`7.221e+07 (3.162)`      | :ranking-low-5:`7.084e+07 (3.103)`      | :ranking-low-5:`8.855e+07 (3.878)`      | :ranking-top-1:`2.283e+07 (1)`          | :ranking-low-5:`2.585e+08 (11.32)`      | :ranking-top-1:`2.283e+07 (1)`          | :ranking-low-5:`8.813e+07 (3.86)`       | :ranking-low-5:`1.216e+08 (5.325)`      | :ranking-top-1:`2.283e+07 (1)`          |
   +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+


<string>:3: (ERROR/3) Error in "table" directive:
unknown option: "widths".

.. table:: FitBenchmarking Results
   :widths: auto

   +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+
   |                                                                                                                                                                                                                   |BFGS                                     |Conjugate gradient (Fletcher-Reeves imp.)|Conjugate gradient (Polak-Ribiere imp.)  |Damped GaussNewton                       |Levenberg-Marquardt                      |Levenberg-MarquardtMD                    |Simplex                                  |SteepestDescent                          |Trust Region                             |
   +===================================================================================================================================================================================================================+=========================================+=========================================+=========================================+=========================================+=========================================+=========================================+=========================================+=========================================+=========================================+
   |`ENGINX 193749 calibration, spectrum 651, peak 19 1 </home/dgk98065/fitbenchmarking/results/short_neutron/support_pages/short_neutron_enginx_193749_calibration_spectrum_651_peak_19_1.html>`__                    | :ranking-low-5:`0.05259 (7.071)`        | :ranking-low-5:`0.08863 (11.92)`        | :ranking-low-5:`0.1199 (16.12)`         | :ranking-top-1:`0.007438 (1)`           | :ranking-low-5:`0.06209 (8.348)`        | :ranking-low-5:`0.02951 (3.967)`        | :ranking-low-5:`0.0737 (9.908)`         | :ranking-low-5:`0.3361 (45.19)`         | :ranking-low-5:`0.404 (54.32)`          |
   +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+
   |`WISH17701 panel 103 tube 3 calibration, peak 1 1 </home/dgk98065/fitbenchmarking/results/short_neutron/support_pages/short_neutron_wish17701_panel_103_tube_3_calibration_peak_1_1.html>`__                       | :ranking-low-5:`0.1254 (14.39)`         | :ranking-low-5:`0.05936 (6.813)`        | :ranking-low-5:`0.05916 (6.791)`        | :ranking-top-2:`0.01014 (1.164)`        | :ranking-top-1:`0.008712 (1)`           | :ranking-top-2:`0.01006 (1.155)`        | :ranking-med-3:`0.01496 (1.717)`        | :ranking-low-5:`0.03498 (4.015)`        | :ranking-top-2:`0.01028 (1.18)`         |
   +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+-----------------------------------------+



Completed benchmarking for short_neutron problem set
```

**Comment by AndrewLister-STFC** [comment]
> This fails for me:

@tyronerees can you check the verson of docutils? I've just spotted that the table directive is from ver 0.3.1

**Comment by tyronerees** [comment]
> > This fails for me:
> 
> @tyronerees can you check the verson of docutils? I've just spotted that the table directive is from ver 0.3.1

`docultils.__version__` gives 0.12, so I would have thought this should be fine(?)

**Comment by AndrewLister-STFC** [comment]
I was looking at the ref docs which say `(New in Docutils 0.3.1)` for the tables directive, but doesn't mention anything on widths. Found the release history just before you commented it

**Pull request merged**
